// Swahili translations of the sung Latin for the proper chants whose scripture reference is a
// deuterocanonical book (Sirach, Wisdom, Tobit, Judith, Baruch) not present in the open Swahili
// Bible, so no verse could be pulled automatically.  Keyed by chant ID.  The Propers tool shows
// these under the chant when no Bible verse is available.
//
// NOTE: these are translations of the meaning of the sung text (not from a published Swahili Bible)
// and should be reviewed by a priest or Kiswahili-speaking choir director before liturgical use.
var swahiliChants = {
  "966": "Yerusalemu, inuka usimame mahali pa juu, uone furaha itakayokujia kutoka kwa Mungu wako.",
  "258": "Kumpenda Mungu ni hekima ya kuheshimika; na wale ambao kwao hekima hujidhihirisha, huipenda mara wanapoiona, katika kuyaona na kuyatambua matendo yake makuu.",
  "1025": "Jicho la Mungu lilimtazama kwa wema, likamwinua kutoka katika unyonge wake, likakiinua kichwa chake; nao wengi wakastaajabu kwa ajili yake na wakamtukuza Mungu.",
  "1135": "Aliwanywesha maji ya hekima, alleluia; hekima itakuwa imara ndani yao wala haitatikisika, alleluia; nayo itawainua hata milele, alleluia, alleluia.",
  "233": "Katikati ya kanisa alifungua kinywa chake, naye Bwana akamjaza roho ya hekima na ufahamu; akamvika vazi la utukufu, alleluia, alleluia.",
  "970": "Huruma ya mwanadamu ni kwa jirani yake, bali rehema ya Mungu ni juu ya kila mwenye mwili; yeye aliye na rehema hufundisha na kuonya, kama mchungaji alivyo kwa kundi lake.",
  "494": "Ndani yangu mna neema yote ya njia na ya kweli; ndani yangu mna tumaini lote la uzima na la wema. Mimi, kama waridi lililopandwa kando ya vijito vya maji, nimezaa matunda.",
  "1300": "Mafundisho nitayaangaza kwa wote kama nuru ya alfajiri, nami nitayahubiri hata mbali sana.",
  "703": "Angalieni ya kuwa sikujitaabisha kwa ajili yangu peke yangu, bali kwa ajili ya wote wanaoitafuta kweli.",
  "172": "Uwape amani, Ee Bwana, wale wanaokungoja, ili manabii wako waonekane kuwa waaminifu; sikia maombi ya mtumishi wako na ya watu wako Israeli, alleluia, alleluia.",
  "1087": "Fanya upya ishara na ubadili maajabu; utukuze mkono wako na mkono wako wa kuume; uharakishe wakati na ukumbuke mwisho, ili wayasimulie maajabu yako.",
  "1257": "Kama waridi lililopandwa kando ya vijito vya maji, zaeni matunda; kama Lebanoni, kuweni na harufu nzuri; toeni maua kama yungiyungi, mtoe harufu nzuri na kuchipua majani kwa neema; imbeni wimbo wa sifa na kumhimidi Bwana katika kazi zake.",
  "104": "Toeni maua kama yungiyungi, mtoe harufu nzuri na kuchipua majani kwa neema; imbeni wimbo wa sifa na kumhimidi Bwana katika kazi zake.",
  "41": "Kwa maneno ya Bwana zimekuwa kazi zake; jua liangazalo huvitazama vitu vyote, nayo kazi yake imejaa utukufu wa Bwana, alleluia, alleluia.",
  "1250": "Miili ya watakatifu imezikwa kwa amani, na majina yao yataishi kizazi hata kizazi.",
  "706": "Mataifa na waihubiri hekima yao, na kanisa litangaze sifa zao.",
  "11": "Mataifa na waihubiri hekima ya watakatifu, na kanisa litangaze sifa zao; na majina yao yataishi milele na milele.",
  "235": "Tazama, kuhani mkuu, ambaye katika siku zake alimpendeza Mungu. Hakuonekana mwingine kama yeye aliyeishika sheria ya Aliye Juu.",
  "456": "Bwana alifanya naye agano la amani, akamfanya kuwa kiongozi, ili heshima ya ukuhani iwe yake milele, alleluia, alleluia.",
  "14": "Bwana alimpenda, akampamba; akamvika vazi la utukufu.",
  "244": "Alimwomba Aliye Juu Sana, Mwenye nguvu, katika kupigana na adui pande zote; naye Mungu mkuu na mtakatifu akamsikia.",
  "1276": "Aliinuka kama moto, na neno lake liliwaka kama mwenge.",
  "1094": "Yeye aliongozwa na Mungu katika kuliongoza taifa kwenye toba; akaondoa machukizo ya uovu, akauelekeza moyo wake kwa Bwana, na katika siku za wenye dhambi aliimarisha uchaji-Mungu.",
  "1196": "Kuhani mkuu, ambaye katika maisha yake aliitegemeza nyumba, na katika siku zake aliliimarisha hekalu; kama moto uangazao, na kama ubani uwakao motoni.",
  "1015": "Simama katika kusanyiko la wazee wenye busara, na ushikamane kwa moyo na hekima yao, upate kusikia kila neno la Mungu.",
  "750": "Msifuni Bwana Mungu wetu, ambaye hakuwaacha wale wanaomtumaini; na kwangu mimi, mtumishi wake, ameitimiza rehema yake aliyoiahidi nyumba ya Israeli.",
  "713": "Umebarikiwa wewe, Bikira Maria, na Bwana Mungu Aliye Juu, kuliko wanawake wote juu ya nchi. Wewe ni utukufu wa Yerusalemu, wewe ni furaha ya Israeli, wewe ni heshima ya watu wetu.",
  "1255": "Wote wakambariki kwa sauti moja wakisema: Wewe ni utukufu wa Yerusalemu, wewe ni furaha ya Israeli, wewe ni heshima ya watu wetu, alleluia.",
  "636": "Roho wa Bwana ameujaza ulimwengu wote; naye yeye anayevishikilia vitu vyote anaijua kila sauti.",
  "861": "Roho wa Bwana ameujaza ulimwengu wote, alleluia; naye yeye anayevishikilia vitu vyote anaijua kila sauti, alleluia, alleluia, alleluia.",
  "646": "Hekima iliwalipa wenye haki ujira wa kazi zao, ikawaongoza katika njia ya ajabu; ikawa kwao kifuniko wakati wa mchana, na mwanga wa nyota wakati wa usiku, alleluia, alleluia.",
  "877": "Waliliimba, Ee Bwana, jina lako takatifu, na wakausifu mkono wako ulioshinda.",
  "312": "Wenye haki waliliimba, Ee Bwana, jina lako takatifu, na wakausifu pamoja mkono wako ulioshinda; kwa maana hekima ilifungua kinywa cha bubu, na kuzifanya ndimi za watoto wachanga kunena vyema.",
  "1332": "Waliusifu pamoja mkono wako ulioshinda, Ee Bwana, alleluia; kwa maana hekima ilifungua kinywa cha bubu, na kuzifanya ndimi za watoto wachanga kunena vyema, alleluia, alleluia.",
  "533": "Wawahurumia wote, Ee Bwana, wala huchukii cho chote ulichokiumba; waachilia mbali dhambi za wanadamu ili wapate kutubu, nawe wawaachilia, kwa maana wewe ndiwe Bwana Mungu wetu.",
  "119": "Ee jinsi ulivyo mwema na mpole, Ee Bwana; Roho wako yumo ndani yetu.",
  "388": "Umetupa, Ee Bwana, mkate kutoka mbinguni, wenye kila anasa na ladha yote ya utamu.",
  "564": "Vitu vyote vilipokuwa katika kimya kikuu, na usiku ulipofikia katikati ya mwendo wake, Neno lako lenye uweza wote, Ee Bwana, lilishuka kutoka mbinguni, kutoka katika kiti cha kifalme.",
  "836": "Roho za wenye haki zimo mkononi mwa Mungu, wala mateso ya uovu hayatawagusa.",
  "98": "Roho za wenye haki zimo mkononi mwa Mungu, wala mateso ya uovu hayatawagusa. Machoni pa wapumbavu walionekana kama wamekufa, lakini wao wamo katika amani.",
  "209": "Roho za wenye haki zimo mkononi mwa Mungu, wala mateso ya uovu hayatawagusa; machoni pa wapumbavu walionekana kama wamekufa, lakini wao wamo katika amani.",
  "835": "Roho za wenye haki zimo mkononi mwa Mungu, wala mateso ya uovu hayatawagusa; machoni pa wapumbavu walionekana kama wamekufa, lakini wao wamo katika amani, alleluia.",
  "658": "Na ijapokuwa mbele ya wanadamu waliteswa, Mungu aliwajaribu; kama dhahabu tanuruni aliwapima, na kama sadaka ya kuteketezwa aliwapokea.",
  "560": "Wenye haki watang'aa, na kama cheche katika mabua watapita huku na huku milele.",
  "1213": "Watakatifu watayahukumu mataifa, na kuwatawala watu; naye Bwana Mungu wao atatawala milele.",
  "1124": "Yeye ni mng'ao wa nuru ya milele, kioo kisicho na doa, na sura ya wema wake.",
  "1362": "Ulipokuwa ukiomba kwa machozi, na kuwazika wafu, na kuacha chakula chako, na kuwaficha wafu nyumbani mwako mchana na kuwazika usiku, mimi niliipeleka sala yako mbele za Bwana.",
  "391": "Tunamhimidi Mungu wa mbinguni, na mbele ya wote walio hai tutamshukuru, kwa maana ametutendea rehema yake.",
  "1303": "Ahimidiwe Mungu Baba, na Mwana pekee wa Mungu, na vilevile Roho Mtakatifu, kwa maana ametutendea rehema yake.",
  "349": "Ubarikiwe Utatu Mtakatifu na Umoja usiogawanyika; tutamshukuru, kwa maana ametutendea rehema yake.",
  "551": "Mungu wa Israeli awaunganishe ninyi, naye mwenyewe awe pamoja nanyi, yeye aliyewahurumia wale wawili wa pekee; na sasa, Ee Bwana, uwafanye wakubariki kwa ukamilifu zaidi, alleluia, alleluia.",
  "581": "Malaika wa Bwana, Rafaeli, alimkamata na kumfunga yule pepo. Bwana wetu ni mkuu, na uweza wake ni mkuu.",
  "227": "Enyi makuhani wa Mungu, mhimidini Bwana; enyi watakatifu na wanyenyekevu wa moyo, msifuni Mungu.",
  "675": "Kama sadaka ya kuteketezwa ya kondoo dume na mafahali, na kama maelfu ya wana-kondoo wanono, sadaka yetu na iwe hivyo mbele zako leo, ipate kukupendeza; kwa maana hakuna aibu kwa wanaokutumaini, Ee Bwana.",
  "965": "Umehimidiwa, Ee Bwana, uzitazamaye vilindi na uketiye juu ya makerubi. Umehimidiwa, Ee Bwana, katika anga la mbinguni; nawe wastahili sifa milele.",
  "1056": "Yote uliyotutendea, Ee Bwana, uliyatenda kwa hukumu ya haki; kwa maana tulikutenda dhambi, wala hatukuzitii amri zako. Lakini ulitukuze jina lako, na ututendee kadiri ya wingi wa rehema zako.",
  "1127": "Enyi malaika wote wa Bwana, mhimidini Bwana; imbeni wimbo na kumtukuza sana milele, alleluia.",
  "67": "Unikumbuke, Ee Bwana, wewe utawalaye juu ya mamlaka yote; utie neno lililonyoka kinywani mwangu, ili maneno yangu yampendeze mfalme.",
  "1047": "Katika mapenzi yako, Ee Bwana, vitu vyote vimewekwa, wala hakuna awezaye kuyapinga mapenzi yako; kwa maana wewe uliviumba vyote, mbingu na nchi, na vyote vilivyomo chini ya anga; wewe ndiwe Bwana wa vyote.",
  "201": "Ndugu, mnifuate mimi, na kuwaangalia wale waenendao kwa kufuata kielelezo mlichonacho kwetu.",
  "1263": "Huyu ndiye aliyekuja kwa maji na damu, Yesu Kristo; si kwa maji tu, bali kwa maji na damu. Wako watatu washuhudiao mbinguni: Baba, na Neno, na Roho Mtakatifu; na hao watatu ni umoja. Nao wako watatu washuhudiao duniani: Roho, na maji, na damu; na hao watatu hupatana kuwa umoja.",
  "933": "Wamchao Bwana na wamtumaini yeye; yeye ndiye msaidizi wao na ngao yao."
};
